#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
选题报告生成器 - 组装周报格式的选题报告
功能：
1. 组装周报格式的选题报告
2. 包含：热点话题、观点对比、选题追踪
3. 可配置推送时间（默认周日晚上）
"""

import os
import json
import logging
from pathlib import Path
from datetime import datetime, timedelta
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, asdict

# 配置日志
LOG_DIR = Path(__file__).parent.parent / "日志"
LOG_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(LOG_DIR / f"topic_report_{datetime.now().strftime('%Y%m%d')}.log")
    ]
)
logger = logging.getLogger(__name__)


@dataclass
class TopicReport:
    """选题报告类"""
    week_id: str                    # 周ID (如 2026-W16)
    start_date: str                 # 开始日期
    end_date: str                   # 结束日期
    hot_topics: List[Dict]          # 热点话题
    viewpoint_conflicts: List[Dict] # 观点对比
    topic_updates: List[Dict]       # 选题追踪
    topic_suggestions: List[Dict]   # 选题建议
    statistics: Dict                # 统计数据
    generated_at: str               # 生成时间
    next_week_plan: str             # 下周计划


class TopicReportGenerator:
    """选题报告生成器主类
    
    生成周报格式的选题报告
    """
    
    def __init__(self, config: Optional[Dict] = None):
        """初始化报告生成器
        
        Args:
            config: 配置字典
        """
        self.config = config or self._load_config()
        self.base_dir = Path(__file__).parent.parent
        
        # 各模块
        self._init_modules()
        
        # 模板
        self.template_dir = self.base_dir / "templates"
        self.template_path = self.template_dir / "选题报告模板.md"
        self.template = self._load_template()
        
        # 输出目录
        self.output_dir = self.base_dir / "输出" / "选题报告"
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def _load_config(self) -> Dict:
        """加载配置"""
        config_path = self.base_dir / "配置" / "选题配置.json"
        
        if config_path.exists():
            try:
                with open(config_path, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except Exception as e:
                logger.warning(f"配置加载失败: {e}")
        
        return {
            'push_time': '20:00',       # 推送时间
            'push_day': 'sunday',       # 推送日 (sunday/saturday)
            'feishu_webhook': '',       # 飞书Webhook
            'top_topic_count': 3,       # Top话题数量
            'top_conflict_count': 3,   # Top冲突数量
            'top_update_count': 5,      # Top更新数量
            'include_suggestions': True, # 是否包含选题建议
        }
    
    def _init_modules(self):
        """初始化各模块"""
        try:
            from topic_cluster import TopicCluster
            from topic_generator import TopicGenerator
            from content_relate import ContentRelater
            
            self.cluster = TopicCluster()
            self.generator = TopicGenerator()
            self.relater = ContentRelater()
            
            logger.info("选题报告模块初始化成功")
        except ImportError as e:
            logger.warning(f"模块导入失败: {e}")
            self.cluster = None
            self.generator = None
            self.relater = None
    
    def _load_template(self) -> str:
        """加载模板"""
        if self.template_path.exists():
            try:
                with open(self.template_path, 'r', encoding='utf-8') as f:
                    return f.read()
            except Exception as e:
                logger.warning(f"模板加载失败: {e}")
        
        return self._get_default_template()
    
    def _get_default_template(self) -> str:
        """获取默认模板"""
        return """📋 {title}

{date_range}

---

## 🔥 热点话题（可追热点）

{hot_topics}

---

## ⚖️ 观点对比（可做对比内容）

{viewpoint_conflicts}

---

## 📌 你的选题有更新（可追踪）

{topic_updates}

---

## ✏️ 选题建议

{topic_suggestions}

---

## 📊 数据统计

{statistics}

---

*本报告由「知识猎手」自动生成*
*Generated by Knowledge Hunter v1.2.0*
"""
    
    def generate(self, 
                 content_list: List[Dict],
                 week_offset: int = 0) -> Tuple[TopicReport, str]:
        """生成选题报告
        
        Args:
            content_list: 内容列表
            week_offset: 周偏移量 (0=本周, -1=上周)
            
        Returns:
            (报告对象, 报告文本)
        """
        # 计算周信息
        now = datetime.now() + timedelta(weeks=week_offset)
        week_id = now.strftime('%Y-W%W')
        
        # 计算日期范围（周一到周日）
        weekday = now.weekday()
        start_date = (now - timedelta(days=weekday)).strftime('%Y-%m-%d')
        end_date = (now + timedelta(days=6-weekday)).strftime('%Y-%m-%d')
        
        logger.info(f"生成 {week_id} ({start_date} ~ {end_date}) 选题报告")
        
        # 1. 热点话题聚类
        hot_topics = []
        if self.cluster:
            try:
                topic_infos = self.cluster.analyze(content_list, week_offset)
                hot_topics = [asdict(t) for t in topic_infos]
                logger.info(f"聚类出 {len(hot_topics)} 个热点话题")
            except Exception as e:
                logger.error(f"热点话题聚类失败: {e}")
        
        # 2. 观点冲突检测
        viewpoint_conflicts = []
        if self.cluster:
            try:
                from conflict_detector import ConflictDetector
                detector = ConflictDetector()
                conflicts = detector.detect(content_list)
                viewpoint_conflicts = conflicts[:self.config.get('top_conflict_count', 3)]
                logger.info(f"发现 {len(viewpoint_conflicts)} 个观点冲突")
            except Exception as e:
                logger.error(f"观点冲突检测失败: {e}")
        
        # 3. 选题追踪
        topic_updates = []
        if self.relater:
            try:
                updates = self.relater.find_updates(content_list)
                topic_updates = [asdict(u) for u in updates]
                logger.info(f"发现 {len(topic_updates)} 条选题更新")
            except Exception as e:
                logger.error(f"选题追踪失败: {e}")
        
        # 4. 选题建议
        topic_suggestions = []
        if self.generator and self.config.get('include_suggestions', True):
            try:
                suggestions = self.generator.generate_from_hot_topics(
                    [{'topic_name': t.get('topic_name', ''), 
                      'keywords': t.get('keywords', []),
                      'sources': t.get('sources', []),
                      'content_count': t.get('content_count', 0),
                      'related_content': t.get('related_content', [])}
                     for t in hot_topics]
                )
                suggestions += self.generator.generate_from_conflicts(viewpoint_conflicts)
                topic_suggestions = [asdict(s) for s in suggestions[:8]]
                logger.info(f"生成 {len(topic_suggestions)} 个选题建议")
            except Exception as e:
                logger.error(f"选题建议生成失败: {e}")
        
        # 5. 统计数据
        statistics = self._calculate_statistics(content_list, hot_topics, 
                                                  viewpoint_conflicts, topic_updates,
                                                  topic_suggestions)
        
        # 6. 下周计划
        next_week_plan = self._generate_next_week_plan(hot_topics)
        
        # 构建报告对象
        report = TopicReport(
            week_id=week_id,
            start_date=start_date,
            end_date=end_date,
            hot_topics=hot_topics,
            viewpoint_conflicts=viewpoint_conflicts,
            topic_updates=topic_updates,
            topic_suggestions=topic_suggestions,
            statistics=statistics,
            generated_at=datetime.now().isoformat(),
            next_week_plan=next_week_plan,
        )
        
        # 渲染报告
        report_text = self._render_report(report)
        
        # 保存报告
        self._save_report(report, report_text)
        
        return report, report_text
    
    def _calculate_statistics(self,
                               content_list: List[Dict],
                               hot_topics: List[Dict],
                               conflicts: List[Dict],
                               updates: List[Dict],
                               suggestions: List[Dict]) -> Dict:
        """计算统计数据
        
        Returns:
            统计数据字典
        """
        return {
            'total_content': len(content_list),
            'hot_topics_count': len(hot_topics),
            'conflicts_count': len(conflicts),
            'updates_count': len(updates),
            'suggestions_count': len(suggestions),
            'by_platform': self._count_by_platform(content_list),
        }
    
    def _count_by_platform(self, content_list: List[Dict]) -> Dict:
        """按平台统计"""
        counts = {}
        for content in content_list:
            platform = content.get('platform', 'unknown')
            counts[platform] = counts.get(platform, 0) + 1
        return counts
    
    def _generate_next_week_plan(self, hot_topics: List[Dict]) -> str:
        """生成下周计划
        
        Args:
            hot_topics: 热点话题
            
        Returns:
            下周计划文本
        """
        if not hot_topics:
            return "暂无明确的下周选题计划"
        
        plans = ["**下周选题计划：**\n"]
        for i, topic in enumerate(hot_topics[:2], 1):
            topic_name = topic.get('topic_name', '未知话题')
            plans.append(f"{i}. 深耕「{topic_name}」话题")
            
            # 添加角度建议
            angles = topic.get('keywords', [])[:2]
            if angles:
                plans.append(f"   - 角度：{angles[0]}")
        
        return "\n".join(plans)
    
    def _render_report(self, report: TopicReport) -> str:
        """渲染报告
        
        Args:
            report: 报告对象
            
        Returns:
            报告文本
        """
        # 格式化热点话题
        hot_topics_text = self._format_hot_topics(report.hot_topics)
        
        # 格式化观点对比
        conflicts_text = self._format_conflicts(report.viewpoint_conflicts)
        
        # 格式化选题追踪
        updates_text = self._format_updates(report.topic_updates)
        
        # 格式化选题建议
        suggestions_text = self._format_suggestions(report.topic_suggestions)
        
        # 格式化统计
        stats_text = self._format_statistics(report.statistics)
        
        # 渲染模板
        return self.template.format(
            title=f"本周选题发现 | {report.week_id}",
            date_range=f"📅 {report.start_date} ~ {report.end_date}",
            hot_topics=hot_topics_text,
            viewpoint_conflicts=conflicts_text,
            topic_updates=updates_text,
            topic_suggestions=suggestions_text,
            statistics=stats_text,
        )
    
    def _format_hot_topics(self, topics: List[Dict]) -> str:
        """格式化热点话题
        
        Args:
            topics: 话题列表
            
        Returns:
            格式化文本
        """
        if not topics:
            return "本周暂无明显热点话题"
        
        lines = []
        for i, topic in enumerate(topics, 1):
            lines.append(f"**{i}️⃣ {topic.get('topic_name', '未知')}**")
            lines.append(f"- 📊 热度：讨论{topic.get('discussion_count', 0)}条，本周增长{topic.get('growth_rate', 0):+0%}")
            lines.append(f"- 💡 切入角度：")
            
            # 添加关键词作为角度
            keywords = topic.get('keywords', [])
            for kw in keywords[:3]:
                lines.append(f"  - {kw}")
            lines.append("")
        
        return "\n".join(lines)
    
    def _format_conflicts(self, conflicts: List[Dict]) -> str:
        """格式化观点对比
        
        Args:
            conflicts: 冲突列表
            
        Returns:
            格式化文本
        """
        if not conflicts:
            return "本周暂无明显观点冲突"
        
        lines = []
        for conflict in conflicts:
            topic = conflict.get('topic', '未知话题')
            va = conflict.get('viewpoint_a', {})
            vb = conflict.get('viewpoint_b', {})
            
            lines.append(f"**「{topic}」**")
            lines.append(f"- 🔴 {va.get('author', 'A')}：{va.get('viewpoint', '')}")
            lines.append(f"- 🔵 {vb.get('author', 'B')}：{vb.get('viewpoint', '')}")
            lines.append("")
        
        return "\n".join(lines)
    
    def _format_updates(self, updates: List[Dict]) -> str:
        """格式化选题追踪
        
        Args:
            updates: 更新列表
            
        Returns:
            格式化文本
        """
        if not updates:
            return "你之前做的选题暂无更新"
        
        lines = []
        for update in updates[:5]:
            lines.append(f"你之前做过「{update.get('user_topic', '未知')}」")
            lines.append(f"→ 本周相关更新：")
            lines.append(f"  - {update.get('source_title', '未知标题')}")
            lines.append(f"  - by {update.get('source_author', '未知')}")
            lines.append(f"  - 💡 建议角度：{update.get('suggested_angle', '')}")
            lines.append("")
        
        return "\n".join(lines)
    
    def _format_suggestions(self, suggestions: List[Dict]) -> str:
        """格式化选题建议
        
        Args:
            suggestions: 建议列表
            
        Returns:
            格式化文本
        """
        if not suggestions:
            return "暂无选题建议"
        
        lines = []
        for i, s in enumerate(suggestions[:8], 1):
            lines.append(f"**{i}️⃣ {s.get('title', '未知标题')}**")
            lines.append(f"- 📐 角度：{s.get('angle', '')}")
            lines.append(f"- 📝 格式：{s.get('recommended_format', '观点')} | 受众：{s.get('target_audience', '')}")
            lines.append("")
        
        return "\n".join(lines)
    
    def _format_statistics(self, stats: Dict) -> str:
        """格式化统计数据
        
        Args:
            stats: 统计数据
            
        Returns:
            格式化文本
        """
        lines = [
            f"- 本周监控：{stats.get('total_content', 0)}条内容",
            f"- 发现热点：{stats.get('hot_topics_count', 0)}个",
            f"- 观点冲突：{stats.get('conflicts_count', 0)}个",
            f"- 选题更新：{stats.get('updates_count', 0)}条",
            f"- 生成选题：{stats.get('suggestions_count', 0)}个",
        ]
        
        # 平台分布
        by_platform = stats.get('by_platform', {})
        if by_platform:
            lines.append("- 平台分布：")
            for platform, count in by_platform.items():
                lines.append(f"  - {platform}：{count}条")
        
        return "\n".join(lines)
    
    def _save_report(self, report: TopicReport, report_text: str):
        """保存报告
        
        Args:
            report: 报告对象
            report_text: 报告文本
        """
        # 保存JSON
        json_file = self.output_dir / f"选题报告_{report.week_id}.json"
        try:
            with open(json_file, 'w', encoding='utf-8') as f:
                json.dump(asdict(report), f, ensure_ascii=False, indent=2)
            logger.info(f"报告JSON已保存: {json_file}")
        except Exception as e:
            logger.error(f"报告JSON保存失败: {e}")
        
        # 保存Markdown
        md_file = self.output_dir / f"选题报告_{report.week_id}.md"
        try:
            with open(md_file, 'w', encoding='utf-8') as f:
                f.write(report_text)
            logger.info(f"报告Markdown已保存: {md_file}")
        except Exception as e:
            logger.error(f"报告Markdown保存失败: {e}")
    
    def get_report_for_push(self, week_offset: int = 0) -> Tuple[str, str]:
        """获取推送用的报告
        
        Args:
            week_offset: 周偏移量
            
        Returns:
            (报告标题, 报告内容)
        """
        # 获取本周监控内容
        content_list = self._collect_week_content(week_offset)
        
        # 生成报告
        _, report_text = self.generate(content_list, week_offset)
        
        # 提取标题
        lines = report_text.split('\n')
        title = lines[0] if lines else "本周选题发现"
        
        return title, report_text
    
    def _collect_week_content(self, week_offset: int = 0) -> List[Dict]:
        """收集本周内容
        
        Args:
            week_offset: 周偏移量
            
        Returns:
            内容列表
        """
        # 从各平台的输出目录收集内容
        content_list = []
        
        platforms = ['小宇宙', 'YouTube', 'B站', 'Twitter']
        
        for platform in platforms:
            platform_dir = self.base_dir / "输出" / platform
            
            if not platform_dir.exists():
                continue
            
            # 查找本周的文件
            for file in platform_dir.glob("*.json"):
                try:
                    with open(file, 'r', encoding='utf-8') as f:
                        data = json.load(f)
                        
                        # 检查是否是本周内容
                        date_str = data.get('date', '') or data.get('published', '')
                        if date_str:
                            try:
                                content_date = datetime.strptime(date_str[:10], '%Y-%m-%d')
                                # 检查是否在周范围内
                                now = datetime.now() + timedelta(weeks=week_offset)
                                weekday = now.weekday()
                                week_start = now - timedelta(days=weekday)
                                week_end = week_start + timedelta(days=7)
                                
                                if week_start <= content_date < week_end:
                                    data['platform'] = platform
                                    content_list.append(data)
                            except:
                                pass
                except:
                    pass
        
        logger.info(f"收集到 {len(content_list)} 条本周内容")
        return content_list


def main():
    """测试函数"""
    generator = TopicReportGenerator()
    
    # 模拟内容
    test_content = [
        {
            'title': 'AI创业的3个机会',
            'author': '张三',
            'date': datetime.now().strftime('%Y-%m-%d'),
            'platform': 'YouTube',
            'viewpoint': 'AI创业机会很多...',
        },
        {
            'title': '程序员如何面对AI替代',
            'author': '李四',
            'date': datetime.now().strftime('%Y-%m-%d'),
            'platform': '小宇宙',
            'viewpoint': 'AI会替代部分工作...',
        },
    ]
    
    report, text = generator.generate(test_content)
    
    print("\n" + "="*60)
    print("选题报告预览")
    print("="*60)
    print(text)


if __name__ == '__main__':
    main()
